### ISSUE TITLE
Custom Task: input area not always visible

### ISSUE THREAD

**Issue by opus1269** [benjaminRomano/grunt-manager#5]
If you have a long list of tasks that scrolls the Custom Task is not visible at the bottom unless you make the pane very high. Would be nice to have that anchored to the bottom and always visible regardless of scroll state.

**Comment by benjaminRomano** [comment]
Should be fixed in v0.1.13.

**Comment by opus1269** [comment]
Fixed. Thanks, and thanks for the responsiveness.

**Comment by opus1269** [comment]
The issue has returned. Maybe due to the 1.2.0 version of Atom?

**Comment by benjaminRomano** [comment]
Yeah. It looks like Atom 1.2.0 broke some stuff. Should be fixed in v0.2.16

**Comment by opus1269** [comment]
Good to go. Thanks again.
